---
title: "Problem Set 1"
author: "Patrick Altmeyer"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output: 
  bookdown::html_document2:
    code_folding: show
    number_sections: false
    toc: true
    toc_float: true
bibliography: bib.bib
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
```

## Problem 1

## Problem 2

```{r}
median_of_means <- function(x, block_size=NULL, delta=.05, permutation_invariant=F, N=1000) {
  n <- length(x)
  if (is.null(block_size)) {
    block_size = round(n/(8 * log(1/delta))) # default block size
  }
  if (!permutation_invariant) {
    x <- x[sample.int(n,n)] # shuffle
    blocks <- split(x, ceiling(seq_along(x)/block_size))
    median_of_means <- median(sapply(blocks, mean))
  } else {
    median_of_means <- mean(
      sapply(
        1:N, 
        function(i) {
          x <- x[sample.int(n,n)] # shuffle
          blocks <- split(x, ceiling(seq_along(x)/block_size))
          median_of_means <- median(sapply(blocks, mean))
          return(median_of_means)
        }
      )
    )
  }
  return(median_of_means)
}
```

```{r grid-setup}
library(rmutil)
library(data.table)
# Parameters
n <- round(exp(5:10))
block_size_ratio <- c(.01,.1,0.5) # block size ratio of sample size n
N <- c(10, 100) # number of random permutations
# Distribution functions:
t1 <- function(...,df=1) {
  rt(...,df=df)
}
t5 <- function(...,df=5) {
  rt(...,df=df)
}
dist_fun <- list(
  "gauss" = rnorm,
  "laplace" = rlaplace,
  "t1" = t1,
  "t5" = t5
)
grid <- data.table(
  expand.grid(
    n = n,
    dist = names(dist_fun),
    block_size_ratio = block_size_ratio,
    N = N
  )
)
```

```{r run-search}
J <- 100 # number of independent samples
P <- nrow(grid) # number of parameter combinations
performance <- rbindlist(
  lapply(
    1:P,
    function(p) {
      list2env(c(grid[p,]), envir = environment()) # load parameters into function scope
      performance <- rbindlist(
        lapply( # loop over J samples 
          1:J,
          function(j) {
            x <- dist_fun[[dist]](n=n) # n random draws from given distribution
            block_size <- block_size_ratio * n
            # Compute the estimates:
            performance <- data.table(
              n = n,
              estimator = c(
                "emp_mean",
                "median_of_means",
                "mom_permutation_inv"
              ),
              estimate = c(
                mean(x),
                median_of_means(x, block_size = block_size),
                median_of_means(x, block_size = block_size, permutation_invariant = TRUE, N=N)
              )
            )
            performance <- merge(grid[p,],performance)
            performance[,sample:=j]
            return(performance)
          }
        )
      )
      return(performance)
    }
  )
)
eps <- data.table(eps=c(0.1,0.025,0.01))
performance <- setkey(performance[,c(k=1,.SD)],k)[eps[,c(k=1,.SD)],allow.cartesian=TRUE][,k:=NULL]
performance[,mae:=abs(estimate)]
performance[,higher_than_eps:=mae>eps]
error_rates <- performance[
  ,
  .(error_rate=sum(higher_than_eps)/.N, mae=mean(abs(estimate))), # error percentage and mean absolute error
  by=.(n,eps,dist,block_size_ratio,N,estimator)
]
saveRDS(performance, file = "data/mean_estimators_performance.rds")
saveRDS(error_rates, file = "data/mean_estimators_error_rates.rds")
```

```{r plot-error-rates}
library(ggplot2)
p <- ggplot(data = error_rates[block_size_ratio==median(block_size_ratio) & N==max(N)], aes(x=log(n), y=error_rate, colour=estimator)) +
  geom_point() +
  geom_line() +
  facet_grid(
    rows = vars(eps),
    cols = vars(dist)
  ) +
  scale_color_discrete(name="Estimator:") +
  labs(
    x="Sample size (logs)",
    y="Probability of error"
  )
p
```

```{r}
library(ggplot2)
p <- ggplot(data = error_rates[block_size_ratio==median(block_size_ratio) & N==max(N)], aes(x=log(n), y=mae, colour=estimator)) +
  geom_point() +
  geom_line() +
  facet_wrap(~dist, ncol=2, scales = "free") +
  scale_color_discrete(name="Estimator:") +
  labs(
    x="Sample size (logs)",
    y="Mean absolute error"
  )
p
```

```{r, fig.height=3.5, fig.width=8}
p <- ggplot(data = error_rates[estimator=="mom_permutation_inv"], aes(x=log(n), y=mae, colour=factor(block_size_ratio))) +
  geom_point() +
  geom_line() +
  facet_wrap(
    N~dist,
    scales = "free_y",
    ncol = 4
  ) +
  scale_color_discrete(name="Block size ratio:") +
  labs(
    x="Sample size (logs)",
    y="Mean absolute error"
  )
p
```

```{r}
p <- ggplot(data = error_rates[estimator=="median_of_means" & N==max(N)], aes(x=log(n), y=mae, colour=factor(block_size_ratio))) +
  geom_point() +
  geom_line() +
  facet_wrap(
    ~dist,
    scales = "free_y",
    ncol = 2
  ) +
  scale_color_discrete(name="Block size ratio:") +
  labs(
    x="Sample size (logs)",
    y="Mean absolute error"
  )
p
```

## Problem 3

## Problem 4

```{r}
random_projection <- function(n,d=2) {
  I <- diag(n)
  w <- matrix(rnorm(2*n), nrow=n)
  A <- I %*% w
  A_stand <- (A - mean(A[,1]))/sd(A[,1]) # center and rescale
  dt <- data.table(A_stand, type="proj")
  v <- matrix(rnorm(2*n), nrow=n)
  dt <- rbind(dt, data.table(v, type="normal"))
  dt[,n:=n]
  return(dt)
}
n <- round(exp(4:9))
dt <- rbindlist(
  lapply(
    n,
    function(i) {
      random_projection(i)
    }
  )
)
p <- ggplot(data = dt, aes(x=V1, y=V2, colour=type)) +
  geom_point() +
  facet_wrap(~factor(n), ncol=3)
p
```

